// Add your dependencies here

dependencies {
    compileOnly("com.github.GTNewHorizons:Botania:1.13.16-GTNH:dev")
    compileOnly("com.github.GTNewHorizons:ArchitectureCraft:1.12.10") {
        transitive = false
    }
    compileOnly("com.github.GTNewHorizons:ForestryMC:4.11.14") {
        transitive = false
    }
    compileOnly("com.github.GTNewHorizons:Backhand:1.8.8:dev") {
        transitive = false
    }
    compileOnly('com.github.GTNewHorizons:Applied-Energistics-2-Unofficial:rv3-beta-911-GTNH:dev')
    compileOnly("com.github.GTNewHorizons:Ztones-Unofficial:2.3.3-GTNH") {
        transitive = false
    }
}
